### ISSUE TITLE
Falsche Prüfung auf PHP memory_limit

### ISSUE THREAD

**Issue by leofeyer** [contao-community-alliance-archive/composer-check#1]
Die Annahme, man könne über `ini_set()` den Arbeitsspeicher beliebig erhöhen, ist falsch. Die meisten Shared-Hoster setzen die Beschränkung nochmal auf Prozessebene, so dass man theoretisch auch `100G` eingeben könnte und trotzdem am Ende nur `128M` hat.

**Comment by discordier** [comment]
ref: https://github.com/contao-community-alliance/composer/issues/162

**Comment by leofeyer** [comment]
Die beiden Tickets beschreiben zwei unterschiedliche Probleme.

**Comment by discordier** [comment]
Daher nur ref und kein duplicate.

**Comment by andreasisaak** [comment]
Wieso nicht einfach: https://github.com/menatwork/syncCto/blob/master/system/modules/syncCto/SyncCtoModuleCheck.php#L79

Damit bekommst du immer den passenden Wert heraus.

**Comment by discordier** [comment]
@andreasisaak weil wir versuchen das limit hochzudrehen. Selbst wenn das auf PHP ebene gelingt, kann dennoch das OS den Hahn zudrehen. Das ist einen Level hoeher.

**Comment by andreasisaak** [comment]
Ja aber was bringt euch das? Prüft doch einfach den reel existierenden Memory Limit und gut ist.

**Comment by discordier** [comment]
Es bringt uns,  dass wir das von PHP vorgesehene Verhalten, naemlich temporaer den Speicher zu erhoehen,  nutzen koennen. Es gibt jedoch Webhoster,  welche dieses unterbinden um mehr Kunden in einen Server zu pressen.
Wenn wir nur pryfen, dann muss der user eingreifen obwohl das zumeist nicht notwendig ist, nur eben bei diesen hostern.

**Comment by leofeyer** [comment]
> Es gibt jedoch Webhoster, welche dieses unterbinden

Und zwar so ziemlich alle, die Shared-Hosting anbieten. Selbst bei einem eigenen Servern wird jeder vernünftige Admin ein Limit konfigurieren, damit ein Angreifer nicht durch eine einfache Fork-Bombe den ganzen Server abschießen kann.

Ich würde daher empfehlen, dem Vorschlag von @andreasisaak zu folgen und den Wert aus der php.ini als gegeben annehmen.
