### ISSUE TITLE
Bitte Composer-Prüfung im Contao-Check prüfen

### ISSUE THREAD

**Issue by leofeyer** [contao-community-alliance-archive/composer-check#2]
Ich habe wie besprochen den Contao-Check um die Composer-Prüfung ergänzt. Das ganze befindet sich im "feature/composer"-Zweig:

https://github.com/contao/check/tree/feature/composer

Die "memory_limit"-Prüfung habe ich bewusst erstmal wieder herausgenommen, bis wir uns auf einen Wert geeinigt haben (siehe dazu #1 und https://github.com/contao-community-alliance/composer/issues/162).

**Comment by andreasisaak** [comment]
Ich habs mal getestet. Das ist alles soweit gut (wie halt der Check von Contao, entspricht ja auch dem bisherigen Layout und dem Prozess).

Mir sind aber noch 2 Punkte aufgefallen. Zum einen wird auf PHP 5.3.2 getestet, Composer selbst verlangt aber mindestens PHP 5.3.4. Das würde ich anpassen.

Und es fehlt mir der Button Composer installieren. Das war eins der Killerfeatures im Composer Check weil die Leute nach einem erfolgreichen Check meistens auch eher bereit sind das ganze zu installieren.

**Comment by leofeyer** [comment]
Also auf der [Composer-Webseite](https://getcomposer.org/doc/00-intro.md#system-requirements) steht PHP 5.3.2.

**Comment by tristanlins** [comment]
Äh, ich müsste noch mal @dominikzogg fragen, es gab irgendeinen Grund warum wir die 5.3.4 vorausgesetzt hatten, wenn das allerdings obsolet ist, können wir das auch reduzieren auf 5.3.2.

**Comment by andreasisaak** [comment]
Joa. Ich bin immer von dieser Zeile ausgegangen:

https://github.com/contao-community-alliance/composer/blob/master/src/system/modules/!composer/config/config.php#L28
